### ISSUE TITLE
Why there is a server?

### ISSUE THREAD

**Issue by stdeson** [awesome-cap/im#3]
A decentralized im system should have only clients, and all data should be stored on the block chain.
How to explain that your system is decentralized?

**Comment by ainilili** [comment]
This service does not use any centralized middleware (such as Redis), nodes communicate with each other using gossip protocol, nodes can be scattered all over the place, and everyone can contribute their own nodes, which I summarize as decentralization, maybe a little different from the decentralization in blockchain.
